#ifndef DBG_H_LIB
#define DBG_H_LIB
#include <stdlib.h>
#include <stdio.h>
#include <stdarg.h>
#include <unistd.h>

static void logger(const char* format, ...) {
    return;
    printf("[[%d]] ", getpid());
    va_list arg_list;
    va_start(arg_list, format);
    vprintf(format, arg_list);
    va_end(arg_list);
    printf("\n");
}

#define msg(code__) ;;
#define dbg_code(code__) ;;
#define handle_error(msg) do { perror(msg); exit(EXIT_FAILURE); } while (0)

#define emit(var_) logger("[dump] "#var_"=%d", (var_));

/*
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;,,,,;;;;;;;;;;;;;;;,,,,;:cloodddddddooolllloooooooooooooooooodddoc:;,'',,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::::::::cccccccccccllllllllloooooooooooooddddkKKXNXKXXKOkkOKXNNX0kxx
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;,,,;;,,;;;;;;;;;;;;;,;;::cloodddddddddo;.........................,lc,..............,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::::::::cccccccccccclllllllllooooooooooooooodk0KXNXKXXK0OOO0KXNX0kxx
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;,,,,,,;;;;;;,,,;;;;;;;;,,;:cloddddddddddddddd:..cdddxddc. ;dxxxxddxxxd:. ...;ddxxxxxxxd:. .;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::::cccccccccccclllllllllooooooooooooooodxOKXXKXXKOO0KK0O0K0kxx
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;,,,,,,,,,;;;;;;,;;;;,;;:cloddddddddddddddddddd;.'OWMMMWWO'.oNMMMMMMMMMW0,   .kWMMMMMMMMWx. .;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::ccccccccccccllllllllllooooooooooooooodk00KXXKOO0KXK0OOkxdx
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;,,,;;;;;;,,;:coddddddddddddddddddddddd;.'OWMMMMWO..oNMMMMMMMMMMXl   ;KWMMMMMMMMWx. .,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::::::cccccccccclllllllloooooooooooooooodxOKX0OO0XNXKX0kddd
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;,,,:loddddddddddddddddddddddddd; 'OWMMMMWO..oNMMMMMMMMMMWx. .oNMMMMMMMMMWx. 'c:,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::::ccccccccccccclllllllllooooooooooooodkOOkO0XNXXXKkddo
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;,,;:loddddddddddddddddddddddddddo; 'OWMMMMWO..oNMMMMMWMMMMW0; 'OWWMWWWMMMMWx. ,ool;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::::::::ccccccccccclllllllllooooooooooooooodxk0XNXKXKOddo
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;,,;;;;;,,,:loddodddddddddddddddddddddddddo; 'OWMMMMWO..oNMMMMWNXNWMMNl.:XWMWXXWMMMMWx. ,oddoc;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::::ccccccccccclllllllllloooooooooooooodx0XXKXKkddo
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;,,,;coodddoododdddddddddddddooodddddo; 'OMMMMMWO..oNMMMMW0O0XMMWk;dNMMNOOWMMMMWx. ,oddddl:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::ccccccccccccllllllllllllooooooooooooodO0KXKkdoo
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;,,,:looooooodddddoodddddddddoccodddooo; 'OWMMMMWO'.oNMMMMWOoo0WMWKx0WMMKoxWWMMMWx. ,odddddoc:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::::cccccccccccccclllllllllllooooooooollodk00kdoo
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;,',:oooooooooooooooooooododddo:cooddooo; 'OWWMMMWO'.oNMMMMMO:,dWWWWXNMMWk:xWWMMMWx. ,oddddddolc;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::::::cccccccccccccllllllllllllloooooooolodxdooo
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,',coooooooooooooooollcccccccc:;:lllccc:' 'OWMMMMWO..oNMMMMWO,.cXWMMMMMMNo'xWWMMMWx. ,odddddooooc;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::;::::::::::::::ccccccccccccllllllllllllllllloloooolllllo
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;,,,',coooooooooooooc:;,''...........'''..... 'OWMMMMWO'.oNMMMMWO' 'OWMMMMMMK;.xWMMMMWx. 'oolooodooooc;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::c:::cccccccccccccllllllllllllllllooolllll
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;,,,',cooooooooooool;......................... 'OWMMMMWO'.oNMMMMMO' .oNMMMMWWk..xWMMMMWx. 'oolcloooooool:;;;;;;;;;;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::ccccccccccccccllllllllllllllloooolll
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;,';coooooooooooooc'......................... 'OWMMMMWO'.oNMMMMMO'  ;KWMMWWXl .xWMMMMWx. ,odolcclooooool:,;;;;;;;,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::ccccccccccccccccccllllllllllllooool
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;,,;loooooooooollol:'......................... 'OWMMMMWO'.oNWWWMWO'  .kWWWWW0, .xWWMMMWx. ,ooooocclooooool;,;;;;;;;;;;;;;;,,,,,,,;;;;;;;;;;;;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::cccccccccccccccclllllllllllllloo
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;looooooooooc:lol;.......................... .xKKKKKKd..c0KKKKKd.   c0KKK0o. .o0KKKK0o. ,oooodolclooooooc;,;;;;;;;;;;;;,,,,,,,,,;;;;;;;;;,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::::::::ccccccccccccccccllllllllllll
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;loooooooooooc:loc,........................... ........  ........    .......   ........ .;ooooooolccooooooc,,;;;;;;;;;;;,,,,,,,,,;;;;;;;,,,,,;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::ccccccccccccccccccclllllcccc
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cooooddoooooo:;loc,'.................',;;;;:::;,,''...........,;;;::;',;;;'.,:,',;;;;;,,:ooooooooolcloooooo:,,;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,;;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::::::::cccccccccccccccccc::::
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;coooooddoooool;;loc,;;..............,:clooooooooooooll;,:::;;clooooool:cooo:,cl:,:oooooocclooooooooolccoooool:,,,,,,;;;;;,,,,,,,,,,,,,,,,,,,,,,,,;;;,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::::cccccccccccccccc:;;:
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,coooooddooooool;;loc;:c,........',;c:;cloooooooooooooooc:lol:cooooooool:cooo:':l:,,:looool:coooooooooolccoooool;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::::cccccccccccccc:;;:
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:loooodddooooooo::lol;:ll;,''''';clol:,:loooooooooooooooc;:cc;;clllooool:cooo:';l:;:;;coooocclooooooooool:cooool:,,;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::::::::ccccccccc:;;:
''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;looooodddoooocclc:lol::loc:lllc;:lool:,;clooooooooooooooc;:cc;;cccccccc::lool;,;ccllc;,:loolcloooooooooool:cloooc;,,;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::::::cccccc:;;;;
,,,,'''''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,cloooooodooool;:ll:col::ll::lool:;cllc:,,:looooooooooooooc:coo:coooooolllloooc:;::codol:,;col:cooooooooooool:cloooc,,;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::::::cccc:;,;;
,,,,,,,,,'''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'',,,,,,,,,,,,,,,,,,,,,,;,,;looooooooooooc;:ll::loc;co:;lool:,;clll;;:clooooooooooooolccoolloooooooooooooccc::lddddol:;coc:looooooooooooc:coool;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;,;;;;;,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::::::::;,,;
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'',,,,,,,,,,,,,,,,,,,,,,,,;coooooooooooooc;:ll:;col::lc;:ccc:;;loooc:::loodooddoddddddoodddddddddddddddddooolooddddddoc;cc:loooooooooooooc:looo:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;,,;;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::;;,,;
,,,,,,,,,,,,,,,,,,,,,,,,,'''''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:looolccoooooooc;:cc;':loc:cc,,:lool:looooolooddddddddddddddddddddddddddddddddddddddddddddddoc;::coooooooooooool::lolc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::;;,,;
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'''''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cooool::looooooc;;:;,',col:;:;;coooooodddddddddddddddddddddddddddddddddddddddddddddddddddddddoc;;clooooooooooool:;lool;,,;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::;,,,,
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:looooc:coooooooc;;;',;;:lolcllllodddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddol;;loooooooooooool::looc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::;,',,
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'''''''',,,,,,,,,,,,,,,,,,,,,,,,,,coolllc:coooooooc;;,,;clccloooddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddo:,cooooooooooooolc;cooc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;,,,,;;;;;;;;;;;;;;;;;;;;;;;::::;;,'',
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''''''''',,,,,,,,,,,,,,,,,,;loooolc:loooooooc;;,,:loooodddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddol:cooooooooooooool;cool;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;::;;;,'',
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''''''',,,,,,,,,,,,,,clooool::loooooooc;,,;loddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddocclooollooooooool::lol:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;,,'',
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cloooolc:loooooooc;,,;ldddddddddddddddddddddddddddddddddddddddddddddolccclooddddddddddddddoollodddolclool:coooooooooc;cooc;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;,;;;;;;;;;;;;;;;;;;;;;;;,,'''
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;lloooolc:loooooool;,,:ooodddddddddddddddddddoooddddddddddddddddddddddoc::ccloooooooooolcc:,'.';ldddlclooc:loooooooool::lol;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;,''''
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:lllooooc:loooooool:,;codoodddddddddddddddooc::codddddddddddddddddddddoc,'',,,,,,,,,,,''......';coddlccol::loooooooooo:;lol:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;,'.''
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:lllooooc:looooooooc,;ldddodooddddddddddol::;;;cloddddddddddddddddddddol;,,,'''......''',;;:clooddddoccol::oooooooooooc;col:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'''',,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;,'..'
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:lllloool:cooooooool;,ldddddddoddodddddolc:;,'..,coddddddddddddddddddddooooooollllclllloooodddddddddoccol:coooooooooooc;cooc;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''',,,,,,,,,,,,,,,,,,,,,,;;,,,,,;;;;;;,,'..'
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:lllllool::loooooool:;lddddddoollllccc:;,'....',:lodddddddddddddddddddddddddddddddddddddddddddddddddoc:lc;coooooooooooc;:ool;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;,,'...
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;llllllolc:cooooooooc:coddool:''''........,;:cooddddddddddddddddddddddddddddddddddodddddddddddddddddoc:lc;coooooooooool;:lol:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;,,;,,''...
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,clllllool::loooooool::odoooc,,,,,;,,;;:cloodddddddddddddddddddddddddddddddddddddoooddooodddddddddddoc:l:;loooooooooool;:lloc;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''...
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:llllloolc:cooooooool:loodoooooooooooodddddddddddddddoooodddddddddddddddddddddddooodoooodddddddddddoc:l::loooooooooool:;loll;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''...
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cllllolll::looooooooc:lddoddddddddddddddddddddddddddo::lddddddddddddddddddddddddddddddddddddddddddoc:c;:ooooooooooool:;clll:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'....
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:llllllllc:cloooooool:codddddddddddoooodddddddddddddooloddddddddddddddddddddddddddddddddddddddddddoc::;cooooooooooool:;clolc,',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'....
''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,cllllllllc:cllooooooc:ldddddddddddooooddoooodddddddddddddddddddddddddddddddddddddddddddddddddddddoc::;loooooooooooolc;cllll:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''...
''''''''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cllllllll:cloollooolccoddddddddoooooddooooddddddddddddddddddddddddddddddddddddddddddddddddddddddoc;;:loooooooooooooc:cllllc;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''''
''''''''''''',,,,,,,'',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;clllllllc:clollllool:cooodddddddoodddoodddddddddddddddddddddddddddddollodddddddddddddddddddddooo:,,cloooooooolllooc:clllllc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,',,,,,,,,'''
''''''''''''''',,,,''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:llllllc:::cllllllllc:loddddddddddddddddddddddddddddddddddddddddddddo:;codddddddddddddddddddoooo:';clloooloollllolc:cllllll:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'',,
''''''''''''''',,,,,''''''''''''''''''',,,,,,,,,,,,,,,',,,,,,,,,,,,,,,,,,,,,,,,',clllllc;:c:cllllllllccoddddddddddddddddddddddddddddddddddddddddddddl:;codddddddddddddddddoodddo:,:lllllllllllllolc;:lllllll:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'
'''''''''''''''',,,,,,,,''',,,,''''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,':lllllc;cl::cllllllll:codddddddddddddddddddollodddddddddddddddddddl::lodddddddddddddddddddddddoc:loolllllllllclllc;:llllllll:,',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''',,,,,,,,'',,,,,,,'''''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,',cllll:;cll::llllllllc:cododdddddddddddddddol:coodddddddddddddddolccodddddddddddddddddddddddool:clllllllllll:;cll:,:lllllllll:,',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''',,,,,,,,,,,'''',,''''''''''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'';lllc;;cllc::llllllllc:coddddddddddddddddddolc:clooddddddddddddooooddddddddddddddddddddoddool;,cllllllllllc;:lll:,;llllllllllc;'',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''',,,,,,,,,,,'''','''''''''''''''',,,,',,,,,,,,,,,',,,,,,,,,,,,,,,,',cllc;;clll:;cllllllllc:cooodddddddddddddddddoolccclodddddddddddddddddddddddddddddddddoooool:',cllllllllll:;clll:';cllll::clllc;,',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''''''''''',,''''''''''''''''''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'';cl:,:cllc:;;cllllllllc:coddddddddddddddddddddddolloddddddddddddddddddddddddddddddoddddooc;,,;clllllllllc;:llll:',cllll:,,;cclc:,',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''''''''''''''''''''''''''''''''''',,,,,'',,,,,,,,,,,,,,,,,,,,,,,,,,,',:c:;:lllc:,,;cllllllllc:cooddooooodddddddddddddddoddddddddddddddddddddddddddooooooooool:;;;,;cllllllllc;;cllll;',:clllc;''';:ccc;'',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''''''''''''''''''''''''''''''''',,,,,,''''',,,,,,,,,,,,,,,,,,,,,,,,,'';c;;ccllc;;,,;cllllllllc::lodooooooodddddddddddddddddddddddddddddddddddddddddoooooool:;,;;,,:llllllllc;;clllll;,,;:cclc:,,,',,:cc:,',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''''''''''''''''''''''''''''''''',,,,,''',,,,,,,,,,',,,,,,,,,,,,,,,,,,',;,:cccc:;,;,,;cllllllllc::looooooooooooooooodooodddddddddddddddddddddooooddooooool:;,,;;,,,clllllllc:;clllllc;',;;:cllc,',,,,,;:c:,'''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
''''''''''''''''''''''''''''''''''''''''''''''',,,''',,,,,,,,,''''',,,'',,,,,,,,,,,''';ccccc:;,,,,,;cllllllllc:;:loooooooooooooodddodddddddddddddddddoooooooooooooolc:;,',,;;,,;cllllllc;,:clllllc,',,,;:ccc;'',,,,',;cc;''''''''''',,,,,,,,'',,'''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''',,,,,''',''''''''''''''''''''''''''''',,,''',,,,,,,,,'''',,,''',,,,,,,,,,'.':cccc:;,,,,,,,,:llllllllc;'';:looooooooooooooooooooooodddddddoooooooooooooolc;'',,'',;;,,:ccclllc;,,:cllccc:,',,,,;:ccc,',,,,,,',::;'',,,,''''','''''''''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
''''''''',,,,,,''''''''',''''''''''''''''''''''',''''''',,,,,,'''',,,,''',,,,,,,,,''';ccccc:;,,',,,,',:cccclllcc:,',,;:cloooooooooooooooooooooddoooooooooooooolc:;,,',;,'',,,',cccclcc;,,,;cccccc:,,,,,,,;:cc:,',,,,,''';:,'',,,,,'',,,,'''''''''''''',,,,,,,,,,,,,,',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
''''''',,,,,,,,,'''''''''','''''''''''''''''''''''''''''''''',,''',,,,''',,,,,,,,,'';cccccc;,,'',,,,,,,::;;cccccc;,,,,,,,;:cloooooooooooooooooooooooooooooolc:;,;;;,',,,'',,,';ccccc:,'',,;:ccccc:',,,,,,,,;:c;,,,,,,,,'';:,'',,,,,,,,,,,'''''''''''''''''',,,,,,,,,''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''',,,,',,,'''''''''','''''''''''''''''''''''''''''''',,,,',,,,,,,,,,,,,,,,,,,;:ccccc:;,'',,,,,,,,,;:;;cccccc;',,,,,,,,;;:clooooooooooooooooooooooolc:;;,;;;;,'',,,'',,',ccccc:,'.',,,;ccccc;'',,,,,,',;::;',,,,,,,'';,'','',,'',,,,,''',,,'''''''''''''''''''''',,,,,,''',,,'',,,,,,,,,,,,,,,,,,,,,,,,
''''''''''''''',,''''''''',''''''''''''''''''''''''''''''''',,,,,,,,,,,,,,,,,,,,,';:cccccc:;'.',;;;,,,'.';:;;:ccccc;',,,,,,',,'';:ccloooooooooooooolc::;;,,;;;;;;;,'',,,'.'',:cccc:,','.',,;:cccc:'',,,,,,'.';::,',,,,,,'',;'''''''''',,,'''''''''''''''''''''''''''''''','',,,'''''',,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''''''''''''','''''''''''',,''''''''''''''','''',,,,,''''',,,,,,,,'';:ccccccc;,.';:::;,,,'..';:;,;ccccc;,',,,,'',,',;;;;;;::ccloooolc:;;,;;;;;;;;;;;;,',,,,,..';cccc:,'',,..',,;:ccc:'',,,,,''..';::,'''',,'',;'',,''''''''''''''''''''''''''''''''''''''''''''''',,,,,''',,,,,,,,,,,,,,,,,,,,,
'''''''''''''',''''''''''',,,,'',,,,,,,,,,,,,,,''''''''''''',,,,,,,,,,,,,,,,,,',;:ccccccc:;'';:ccc;,,,'..'.,::,;:cccc:,',,,'',,'';;;;;;;;,,;;;;;;;;;;;;;;;;;;;;;;;,',,,,,..,cccc:;'',,,'.',,;:ccc:,'',,,,'....';:;'.......',''''''''''''''',,,''''''''''''''''''''''''''''''''''''''''''',,,,,,,,,,,,,,,,,,,
''''''''''''''''''''''''''''''''',''',''''',,'''''''''''''''',,,,,,,,,,,,,,,,',;ccccccccc;,,;:cccc:,,,'.''..,::,,:cccc:;'''''','',;;;;;;;;;;;;;;;;;;;;;;;;;;;::cc:,,,,,,'',:cccc;'',,,,,'.',,;:cc:,'',,,,,'....',:;'.......,......'''''',,,,,,'',,,',,,,'''''''''''''''',,''''''''''''''''''',,,,,,,,,,,,,,,
''''''''''''''''''''''''''''''''',''''''''''''''''''''''''''',,,,,,,,,,,,,,'',:::ccccccc:,,:ccccc::,,,'..'..';::,';:ccc::,''.','';:;;;;;;;;;;;;;;;;;;;;;;::clloooc,'''''';:cccc:,'',,,,,''.',,;:cc;'',,,,,,''...',:;'......'.............'''''''''''',,''''''''''''''''',,,'''''''''''''''''''''',,',,,,,,,,
''''''''''''''''''''''''''''''''''''''''''''''''''''''''',,,,,,,,,,,,,,,,,',;:ccc::::ccc;,;:cc:::::;,''....''';::,',:cccc:;'.',',cllcc::;;;;;;;;;;;:::ccllooooooo:'';;,',:ccc::,'',,,,,,,'..'',:cc:''','',,,''....,:;'....'.......................'''''''',,'',,,,,'''''''''''''',,,,,,,''''''''''''''''''',
''''''''''''''''''''''''''''''''''''''''''''''''''''''''',,,,,,,,,,,,,,,',;::c:::;;::cc:;;:cc::c:::;,'.....''',::;,'';:cccc:;,'';looooollccc:::::cclloooooooooooo:',lo:;::cccc;''',,,,,''''...';:c:;''''''''''.....,;;'...'..............................'',,,,,,,,,'''''',''','',,,,,,,'''',,''''''''''''''
''''''''''''''''''''''''''''''''''''''''''''''''''''''''',,,,,,,,,',,'',;::c:;,,;::::::;,::ccccc:::,,'..'..'''';::;,'',;ccccc:,';looooooooooooooooooooooooooooooo:,';:;;:cccc:,'',,,,,,,,''''..,::::'.'''''''''....',:;'..................................'',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''''''''
''''''''''''''''''''''''''''''''''''''''''''''''''''''',,,,,,,,,,,''',,;::;,,',;::::c:;,;:::::::::;,''.''.''''',:::;,,'',:ccccc:;:looooooooooooooooooooooooooooool;''.,:cccc:;'.',,'',,,,,,'''.';:::;'.'''''''''....';::,.................................'',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'''''''
'''''''''''''''''''''''''''''''''''''''''''''''''',,,,,,,,,,,,,,''',;::;,,''',::::::::,,::::::::::;,''''''''''''::c:;,,'.';ccccc::;cooooooooooooooooooooooooooooooc;;',:cc:::,,;;,'''',,,,''''.';::::,.'''''''''.....,;:;'................................'',,,,,,,,,,,,,,,,,,,,,,'''',,,,,,,,,,,,,,,'''''''
'''''''''''''''''''''''''''''''''''''''''''''''''',,,,,,,,,,,'''',;;;,,'',',;::::::::;,;::::::::::;,'''''''''''';::::;,,'',;:ccc:c:;:looooooooooooooooooooooooooool::;,:ccc::,,col:;,''''''''''';::::;'.''''''''.....';::;'...............................',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'''''''
''''''''''''''''''''''''''''''''''''''''''''''''''',,,,'',,''',;;:;,''','',;:::::::::,,;:::::::::;,'''''''''''.,::::::;,';::;:cccc::;:looooooooooooooooooooooooooooll:;:ccc::,';oooolc:;,''''''';:::::,.''''''''......,;::;'..............................'',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''''''''''''''''''''''''''''''',''''',,,,''',''',;;;,'',,,'',;:::::::::;,;::::::::::;,'''''''',;;',:::c:::;',co:;:cc:cc:;:ooooooooooooooooooooooooooooooc;;:ccc:,',:looodoolc;,;,',::::::,.''''''''......';;::;'.............................'',,,,,,,''',,,,,,,,,,,,,,,,,''',,,,,,,,,,,,,,,,,,
''''''''''''''''''''''''''''''''''''''''''''''',,'''''',,'',;;;'',,,,,'',;:::::::::;,,;::::::::::,''''',::cool;;::::::::,,coo:;::ccc:;;loooooooooooooooooooooooooooooo:;:cc::;,;;;:looool:;cl:,;::::::,..'''''''......',;::;'.............................'',,,,'''''',,,,,,,,,,,,,,,,,''',,,,,,,,,,,,,',,,'
'''''''''''''''''''''''''''''''''''',,'''''',,,,,,,''''''',;;,'',,,,,'',;::::::::::;,,::::::::::;,',;:loooodoc;:::::::::;,cooo:;::cc:;,cooooooooooooooooooooooooooooool:;:::::;:::;;;;::;,:l:,;:::::::,...............'';:::,.............................'',,,'''''',,,,,,,,,,,,,,,,,,'',,,,,,,,,,,,'''''''
'''''''''''''''''''''''''''''''''''''''''''''''',,,'',,'',;;''',,,,,'',;:::::::::::;,;:::::::;,,;:clooooooool;;:::::::::;,coddl;;:cc:;,:oooooooooooooooooooooooooooooooc,,::::::::::::::;;c:,;::::::::;................';;::,...''........................',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
''''''''''''''''''''''''''''.''''''''''''''''''''''''''.',,'',,,,,,,',;::::::::::::;,;::::;;,'..':looooooooo:,;:::::::::;,coddo:,::cc:,,cloooooooooooooooooooooooooooooc,;:;:::::::::::;,;;;::::::::::,................',;::,.............................',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''''''''''''''''''''''''''''''''''''''''''.''..''''''''';::::::::::::::;;,''.........,:looooooc;;::::::::::;;cooooc,;:::;;cc:::clllooooooooooooooooooolc::;,coc:;;;;;;;;;,,,;;:::::::::::,;;........','...',;:;,......'......................',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''''''''''''''''''''''''''''''''''''''''''...'''''''''',:::::::::::::;,'...............,cooooo:;;:::;,;::::;;coodo:,;::;,cool:;;:cc::clooooooooooooooollllc;cddolccc::;;,,,;::::::::::::;,:c,........;c;'.';;;;'........''...................',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''''''''''''''''''''''''''''''''''''''''''...''''''''',;:::::::::::;;::;,................:lool;;::::;,,;::::,;llc:,';:;,:odddoocclllllloodooooooooooooooooc:coddolc::;;;;;:::;;;::::::::;;co;.........:l:,';:;,..............................',',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''''''''''''''''''''''''''''''''''''''''''...'''''''.';;:::::::::;,;cooooc;...............;lol:;:::::;,',;;;,',;;,',;,;codddddddocclooooooooooooooooooooooc;cddddoc:;,,;;;;;;;,,:::::::;,:lo:.........,loc,,;;'..............................',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
''''''''''''''''''''''''''''''''''''''''''''''''''''''''..'''''''',;;::::::::;;cloooooool;..............,ll:,;:::::;,''',,;;;;'.,;cloddddddddddlcccloooooooooooooooooooc;cdddddddooolllllc;,;:::::::,;looc..........;lol;''...............................',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''.''''''.';;:;;::::;;:loooooooooooc,.............,cc;;:::;;;;;;,,,,,;,'',;::::::;codddddoocccllooooooooooooooooc;ldddddddddddddoc,,;::::::;,;loooc'..........cool;.....................'..........',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''''''''''''''''''''''''''''''''''''''''''','.'''''.,;;;;;:::;;:lododdddoodoool;.............,c:,;;;;,',;:::;;;;;;;;;;;,,,;:lodoodddddolccccloooooooooooooc:lddddddddddolc;;;::::::;;,;looooo:..........;loolc:::;,..........................',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''''''''''''''''''''''''''''''''''''''''''',,'.''''',;;;;:::;,codddddddddddooooo:.............';;;;;;,'',;;::::;;,'',;:cllodddddddddddddoooc::cooooooooooo::oddddddddol:,',;;;;;;;::cloodooool,.........'cooooooool;.........................'',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''''''''''''''''''''''''''''''''''''''''''',;,'.'''';;;::::;;codddddddddddddddoooc'............',,;;;;'.'',;:::::;;;;;;:::::ccccccloddddddddolc:cloooooool:coddddddddollccccccclllooooodoooooo:..........coooooooool;........................'''''''''''''',,''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,
''''''''''''''''''''''''''''''''''''''''''''''''''''''''';;,''''';::::;;;loddddddddddddddddodooc'.............,,;;;'..'',;;::::::::::;;;;;;,,,:lodddddoddddooc::clooooc;cooooooooooooooooooooooooooooooooool'.........:ooooooooool,.......................''''''''''''''''''''''''''''''''',,,,,,,,,,,,,,,,,
''''''''''''''''''''''''''''''''''''''''''''''''''''''''',;;,'..,;;;:;,:loddddddddddddddddddddooc,.............,,;;,',,'.',;:::::::::::;;;;:cloddoooddddodddddol:;:looc:loodoooooooooooooooooooooooooooooooo;.........;oooooooooool:;,'...................''''''','',,,'''''''''''''''''''''''''''''''''''''
''''''''''''''''''''''''''''''''''''''''''''''''''''''''.',;;,'.';;;;;:oddddddddddddddddddddddoooc,............';,;;;,;::;,,,;;;;;;,,;;;:clooooooooooooooolllloool:::::;lool:;;,,;::cclloooooooooooooooooooo:.........;loooollooooooolc;..................'''''''''''',,,,,',,,,,,,,'',,,,,,,,,'',,,,,,,,,,,
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''.',;;;;,,,,;coddddddddddddddddddddddddoooc,............,:;,,;,;:lllcccc:::ccclooddoooooooool::;''.''''',,,'...':;'.............',;;:cclllooooooooooc'........,loooc:cooooooooooc'...............'','''''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''',;;;;;,;lodddddddddddddddddddddddddooooc'............,cc:;;,,;;cooddddoooooooodooooolc;,..............................................',;;:ccllll,........;looc:;coooooooooool;'.............'',''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''',;;;:ldddddddddddddddddddddddddddddooo;.............;lolcc:;,,:loooooooooooooolc;,.................................................. .......'',..........,::;;;clooooooooooool:'...........'',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''',,''',:oddddddddddddddddddddddddddddddoool;.............;looooolllooooooooooolc:,..............................................................................',;:loooooodddoooool:,.........',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
''''''''''''''''''''''''''''''''''''''''''''''''''''''''',,,''',codddddddddddddddddddddddddddddddooooc'.............;loooooooooooooolc:,'..........................................................  ........................;loooooooddooooooooc;'......',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''';looodddddddddddddddddddddddddddddddoooo:..............,looooooooolc:,'............................ .....         ...................       ..        ..........':looooooooooooooooolc;,...',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''''''''''''''''''''''''''''''''''''''''''',''',:odddddddddddddddddddddddddddddddddddooool,..............,cooooolc;'.....................        .........          ....          .     ...              ..........':loooooooooooooooooolc;'.',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''''''''''''''''''''''''''''''''''''''''''',',:looddddddddddddddddddddddddddddddddddddddoo:...............':ll:;'................   ....... ......... ....            ....                                   ........':looooooooooooooooooo:'.',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
''''''''''''''''''''''''''''''''''''''''''''''''''''',''';loodddddddddddddddddddddddddddddddddddddddoool,...........   ..'..................       .............   ...               ...                                  .  .......':loooooooodddddooooc;;:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''''''''''''''''''''''''''''''''''''''',''':looodddddddddddddddddddddddddddddddddddddoooooo:..........     . ...  .                     ......       ....                ....                                   .........,cooooooddddddooool;col:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''''''''''''''''''''''''''''''''''''''''',cooddddddddddddddddddddddddddddddddddddddddolloool,.......          ..                                     ...                   ...                                    .........;loooooddddddoool:cooc,',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''''''''''''''''''''''''''''''''''',,'',:lodddddddddddddddddddddddddddddddddddddddddoc:coooo:......                                                  ...                    ...                                    .........,coooddodddddooc:lool;,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;,,,,,,,,,,,,,,,
''''''''''''''''''''''''''''''''''''''''''''',,,,'',cooodddddddddddddddddddddddddddddddddddddddddo:;cooooc'...                                                   ....                     ...                                    .........'coooooodddddoccoool:,,;;;;,,,,,,,,,,,,,,,,,,,,;;;;;,,,;,,,,,,,;;;
''''''''''''''''''''''''''''''''''''''''''''',,''';loddddddddddddddddddddddddddddddddddddddddddddl;,cloool,..                                                    ...                       ...                                     ........,looooooddddl:coool,,;;;;;;,,,,,,,,,,,,,,,,,,,,,;;;,,,;;;;;;;;;;;
'''''''''''''''''''''''''''''''''''''''''''',,'',:loodddddddddddddddddddddddddddddodddddddddddddo:,;cloooc'.                                                     ...                        ...                                     ........;looooooodoc:loooc'',,;;;;;;;,,,;;,,,,,,,,,;,,,,,,,,,,;;;;;;;;;;
'''''''''''''''''''''''''''''''''''''''''''','.'coodddddddddddddddddddddddddddddoooddddddddddoool;,;coool,.                                                      ...                         ...                                       ......:ooooododl:coooo:'''',,;,;;,;;;;;,,,,,,,,,,,,,,;,,,,,,,,;;;;;;;
'''''''''''''''''''''''''''''''''''''''''','',;;cooooddoddddddddddddddddddddddddolldddddddddddoo:,;;clol,.                                                       ...                          ..                                       ......,loooodoo::oodol:,;,,''',;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,;;;;;;
'''''''''''''''''''''''''''''''''''''''''''';loc:ldddddddddddddddddddddddddddddolcodddddddddddoc,,;;clc,.                                                        ...                          ...                                       ......cooooooc;looool;,;,,,''',;;;;;;;;;;;;;;;;;;;;;;;;;;,,;;;;;;;;;
''''''''''''''''''''''''''''''''''''''''''',coooccoddddddddddddddddddddddddddddlccoddddddddddol;,;;:cc'.                                                        ...                            ..                                       ......:oooooc;cooooo:,,;;,,,,,'',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
''''''''''''''''''''''''''''''''''''''',,''':oooocclddddddddddddddddddddddddddocclodddddddddoo:,;;;;;'.                                                         ...                            ...                                      ......:ooool::looool;,,,,,,;;cc;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
'''''''''''''''''''''''''''''''''''''',,,''',:oddol:lodddddddddddddddddddddddoc:codddddddddooc,,;;;,''..                                                        ...                             ..                                      ......:ooooc:loooooc,,;;,,,;clol:,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
'''''''''''''''''''''''''''''''''''''',,,,'''';looolccloodddddddddddddddddddol:clodddddddoooc;,;;,'''''..                                                       ...                             ..                                     .......:oooc:coooool;,,;,;,;:looolc;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
''''''''''''''''''''''''''''''''''''',',,''''',;coodolcclddddddddddddddddddol::loddddddddool;,;;,''',,,'..                                                       ..                              .                                      ......:ooc:coooodoc,,;,,;;:llooolll:,,;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,
''''''''''''''''''''''''''''''''''',,,,,''',,;,,,:looooc:loddddddddddddddool::cooddddddoool:,;,''',,,,'''..                                                      ..                                                                        ..'clc:cooooooc;,,;;;;cloooooooolc;,;;;;;;;;;;;;;;;,,,,,''''''...
'''''''''''''''''''''''''''''''''',,,,'',:c:;,,,,,,:looolcccloddddddddddooc::cooooddddoooo:,,,''',,,,,,,,'..                                                                                                                               ..,:::looooool;,,;;;;cloooooooooool:,,;;;,,,,,,''''''............
'''''''''''''''''''''''''''''''',,,,''';clll:;;,;;,,;:cooolc:codddddddoolc::cooddodddddoo:,,''',,,,,,,,,,,'..                                                                                                                              ...,clooooool;,,,;;:cloooooooooooool:,'''''......................
''''''''''''''''''''''''''''''',,,,'',:loolllc;;;;;;;,,;cloooc:lodooooolc::clooodooooooo:'.'',,,,,,,,,,,,,,'.                                                                                                                              ..;loooooool;,,;;;:llooooooooooooooolc,..''......................
'''''''''''''''''''''''''''''',,''',:lloooooolc:;;;;;;;,,,cooolcccooool:::clodoooooodooc'.',,,,,,,,,,,,,,,,,'.                                                                                                                            .,cooooooooc;,,;;:cloooooooooooooooooolc,..''''''.................
''''''''''''''''''''''''''',,',''';cloooooooooolc:;;;;;;;,,;cooolccllc:;:cloooooooooool,.',,,,,,,,,,,,,,,,,,,..                                                                                                                         ..;loooooool:,,,;;cloooooooooooooooooooollc,..''''''...'.......'''''
'''''''''''''''''''''''''''',''',:llooooooooooooolc;;;;;;;,,,:loool;,,;:cloooooooooool;',,,,,,,,,,,,,,,,,,,,,'.                                                                                                                        .,cloooooooc;,,,;:clooooooooooooooooooooolll;..''''''''''''''''''',,,
''''''''''''''''''''''''''','',:lloooooooooooooooool:;;;;;;;,,;:clc:,,',clooooooooool;',,,,,,,,,,,,,,,,,,,,,,'..                                                                                                                      ..,:loooool:,'',;cloooooooooooooooooooooooool;..'''''''''''',,,,,,,,,,
'''''''''''''''''''',,'',,,',:lllllllooooooooooooooolc:;;;;;;,,,',,;;;:::::ccclooool;',,,,,,,,,,,,,,,,,,,,,,,,'..                                                                                                                   .....',:cll:,'''.':looooooooooooooooooooooooooc,.'''',,,,,,,,,,,,,''''''
'''''''''''''''''''',,,,,'';cllooooooooooooooooooooooolc:;;,;,,'.'''',cloolccccccc;'',,,,,,,,,,,,,,,,,,,,,,,,,,,..                                                                                                               .....''''''',,''''',:lloooooooooooooooooooooooool:',;;;;;;;,,,,,'''''''''''
''''''''''''''''''',,,,'',:lllooooooooooooooooooooooooollc:;''''',,,,',;;:cclllllc,.',,,,,,,,,,,,,,,,,,,,,,,,,,,,..                                                                                                            .......''''''''''''',cllooooooooooooooooooooooooolc;,;;,,,,,'''''''''''''''''
''''''''''''''''',,''''',:llloooooooooooooooooooooooooooolc,.',,,,,,,,,,,,,,,,,,,'',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..                                                                                                         ....''..''''''''''''',cooooooooooooooooooooooooooolc;',,,,'''''''''''''''''''''
''''''''''''''''',,,'''':llloooooooooooooooooooooooooooool;'',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..                                                                                                        ....'''''''''''''''',:loooooooooooooooooooooooooooc;'',,,,'''''''''''''''''''''
''''''''''''''''',',,'';llllloooooooooooooooooooooooooooolc;'',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..                                                                                                       ...''''''''''''''''';loooooooooooooooooooooooooooc;,,,,,,,,,,,,,,,,,,,,,,,,,,,,
''''''''''''''',,,,,,'',:llllooooooooooooooooooooooooooooool;'',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..                                                                                                      ..'''''''''''',,,,,;clooooooooooooooooooooooooool;,,;,,,,,,,,,,,,,,,,,,,,,,,,,,
''''''''''''',,,,,,,,,,',:loolooooooooooooooooooooooooooooool;'',,;,,,,,,,,,,,,,,,,,,,,,,,,,,,,'............','........                                                                                                      ..''''',,,,,;;;;;;;:lllooooooooooooooooooooooool;,',,,,,,,,,,,,,,,,,,''',,,,,,'
'''''''''''',,,,,,,,',,,',:llloooooooooooooooooooooooooooooool:',,,,,,,,,,,,,,,,,,,,,,,,,,,,'....',;:::;,'.. .  .............................    .........  ...............       ........   ...............                 .',,,,;;;::::::;;;,:lollooooooooooooooooooooool:,,;;;;;;;;;;;;;;;;;,,,,,,,,,,,;
'''''''''''',,,,,,,''',,,',:lllloooooooooooooooooooooooooooooll;',,,,,,,,,,,,,,,,,,,,,,,,,'. .;d0XNWWWWWNX0xc.  :0XXXXXXXXXXXXXXXXKdckXXXXXKo.  'xXXXXXXXd..oKXXXXXXXXXXXK0ko,.  .lKXXXXXO, .dXXXXXXXXXXXKKOxc'              .,,;;;;;;;;;;;;;;;,:lllloooooooooooooooooooool:;;::;;:::;;;;;;;;;;;;;;;;;;;;;;:
''''''''''''''''''''',,,,,,';cllloooooooooooooooooooooooooooollc;',;,,,,,,,,,,,,,,,,,,;,,,. 'xNWWWMMWWWWWWWWNx'.lNMMMMMMMMMMMMMMMWWkl0WMMMMWx.  'OWWMMMMWk..dWMMMMMMMMMMMMMMWXd' .dNMMMMWK; .kWMMMMMMMMMMMMMWWKl.           ..',,,,,,,,,,,,,,,,,cllloooooooooooooooooooolc;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
''''''''''''''''''''',,,,,,,',:llloooooooooooooooooooooooooollllc;,,,,,,,,,,,,,,,,,,,,,,,. .dNWWWWWKdcoKWWWMWNd'cXWWWWWMMMMMMWWWWWNxl0MMMMMWx.  'OWMMMWWWk..dWMMMMMWKO0NWMMMMWNx..dNMMMMMK: .kWMMMMMN0O0NWMMMWWXo.          ..'',,,,,,,,,,,,,,,;llloooooooooooooooooooolc;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
''''''''''''''''''''',,,,,,,,'';clloloolooooooooooooooooooooooollc;,,,,,,,,,,,,,,,,,,,''.. ,0WMMMWNo. .lXWWWWWO,.;:::l0WWMMMWKo::::':0MMMMMWx.  'OWMMMMMWk..dWMMMMWKc..c0WMMMMWK:.dNMMMMMK; .kWMMMMM0,..:0WWMMMW0;         ..''',,,,,,,,,,,,,,,:lloooooooooooooooooooolc;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''''''''''',,,,,,,,,,,,,',:llloolooooooooooooooooooooolllllc;,,,,,,,,,''''''''''... ,0WMMMWW0:. .,:::;;,.  .  .kWMMMMW0,     ,0MMMMMWx.  'OWMMMMMWk..dWMMMWWK;  .xWMMMMWNl.dNMMMMMK; .kWMMMMMO'  .dWWMMMMXl         ..',,,,,,,,,,,,,,,,,:llooooooooooooooooolool;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
'''''''''',,,,,,,,,,,,,,,,,,,,,,,,;clllllooooooooooooooooooooolllllc;'''''''''''''''''''.. 'kWMMMMWWN0xc;.     ..... .kWMMMMM0,     ,0MMMMMWx.  'OWMMMMMWk..dWMMMWWK:..:0WMMMWWX:.dNMMMMWK: .kWMMMMMO'  .oNMMMMMNo.       ..',,,,,,,,,,,,,,,,,,clloooooooooooooooooool:,,;;,,,,,,,,,,;;;;,,,,,,,,;;;;;;,,,,,
''''''''''',,,''',,',,,,,,,,,,,,,,',:clolllloollooooooooooooollllllll:,'''''''''''''......  ;OWWWWWWMWWWNKko,. ..... .kWMMMMM0,     ,0MMMMMWx.  'OWMMMMMWk..dWMMMMWN0k0XWWMMMWNx..dNMMMMMK: .kWMMMMMO'   lNMMMMMNo.       ..,,,,,,,,,,,;;;;;,,;looooooooooooooooooolc;,,;,,,,;;;;;;;,,,;;,,,,;;;;;;;;,,;;;;;
,,,'''''''',,,'',,'',,,,'',,,,,,,,,,,,:lllllllllllloooooooolllllllllll:'.'''''''''.......... 'lOXWWWMMMMMMWWXk,  ... .kWMMMMM0,     ,0MMMMMWx.  'OWMMMMMWk..dWMMMMMMMWMMWWWMWXd' .dNMMMMMK: .kWMMMMMO'   lNWMMMMNo.       .',,,,,,,,,,,,,;;,,,:lolloooooooooooooooll:,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
,,,'''''''',,,,,,,'',,,,,,,,,,,,,,,,''';cllllllllllllllllllllllllllllll:,''''''''''''''''....  .,cdOXNWMWWWWWW0;  .. .kWMMMMM0,     ,KMMMMMWx.  'OWMMMMMWk..dWMMMMWWNNNXXKOxl,.  .dNMMMMMK: .kWMMMMMO'   lNMMMMMNo.      ..,,,,,,;;,,;;;;;;;,,clllloooooooooooooool:,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
',''''',,,,,,,,,',''''''''''''''''''''''';cllllllllllllllllollllllllllllc;''''''''''''''.. ...   ...':xXWWMMMMWx. .. .kWMMMMW0,     ,0MMWWMWx.  'OWMMMMMWk..dWMMMMWXl''....      .dNMMMMMK: .kWMMMMMO'  .oNMMMMMNl      ..',,,,,,,,,;;;;;;;,,;clllloooooooooooooolc;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
''''',,,,''''''''''''''''''...''..'''''...';clllllllllllllllllllllllllllll;'''''''''''''.  :kOOOOOd'  .oNWMMMMWk. .. .kWMMMMM0,     ,0WWWMMWk.  'OWMMMMMWk..dWMMMMMK;            .dNMMMMWK; .kWMMMMMO'  .kWWWMMMXc      ..,,,,,,,,,,,;;;;;;;,:lllooooooooooolllllc;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
''''''''''''''''''...'......................,:lllllllllllllllllllllllllllll:''''''''''''.  lXWMMMWXo...dNWMMMWNd. .. .kWMMMMW0,     .xNWWMMM0:..cKWWMMMMNo..dWMMMMMK;            .dNMMMMMK; .kWMMMMMKl;:xXWWWMWWO'      .,;,;,,,,,,;;;;;;;;,;clloooooooollllllllc;,;;;:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::;;;;;;
..........................................''.',:llllllllllllllllllllllllllll:,''''''''''.. ,OWWWMWWN0OKNWWWWWWO, ... .kWMMMMW0,      ;0WWMMMWX00XWWMWWWWO' .dWMMMMMK;            .dNMMMMMK; .kWMMMMMWWWWWWMMMMW0;      .',,,,,;;;;;;;;;;;;,,:lllloloooooolllllll:;;::;;;;;;;;;;;::;;;;;;;;;;;;;::;;;;;;;;;;;
........................................''.''..',:lllllllllllllllllllllllllllc;''''''''''.. ,xXWWWMMMMMMMMWNKd' ..'. .kWMMMMW0, ..    ;kXWWMMMMMWMMMWX0x'  .dWMMMMWK;            .dNMMMMMK; .kWMMMMMMMMMMMMWNKd,      ..,;;;;;;;;;;;;;;;;;,;cllllllloooooolllllc;;;;;;;;;;;;::::::;;;;;;;::::::::;;;;;;;;:::
........................................'''''''''';clllllllllllllllllllllllllll:,''''''''''...'coxkkOOOkkdl;....'''. .:ddddddc. ..     .,cdxkOOOOkxoc'..    ;odddddl.             ;odddddl. .:ddddddddddddol;.       ..';;;;;;;;;;;;;;;;:;,:lllllllooooolollllc;;:::::::::::;;;;;;;;;:::::::::;;;;;;:::::::;
..........................................'''''''''':lllllllllllllllllllllllllllc,.'''''''''..     .....    ..'',,,'.           ..          .....                                                                    ..,;;;;;;;;;;;;;;;:;,;clllllloooooollllll:,;:::::::::;;;;;;;:::::::::::;;;;:::::::::::;

*/

#endif